# Generated by Django 4.2.6 on 2023-12-23 04:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
