# Generated by Django 4.2.6 on 2023-12-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='ck',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
